language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-mirage.sh
script: bash ./.travis-mirage.sh
env:
  matrix:
    - OCAML_VERSION=4.02 MIRAGE_BACKEND=unix FLAGS="-vv --net=direct --dhcp=true"
